echo "{\n    \"zone\": \"TW\"\n}" >          ./gen/ASffaa_0_1601/geolocation.json
echo "{\n    \"zone\": \"US-MIDA-PJM\"\n}" > ./gen/ASffaa_0_1201/geolocation.json
echo "{\n    \"zone\": \"KR\"\n}" >          ./gen/ASffaa_0_1401/geolocation.json
echo "{\n    \"zone\": \"US-MIDA-PJM\"\n}" > ./gen/ASffaa_0_1004/geolocation.json
echo "{\n    \"zone\": \"JP-TK\"\n}" >       ./gen/ASffaa_0_1006/geolocation.json
echo "{\n    \"zone\": \"SG\"\n}" >          ./gen/ASffaa_0_1007/geolocation.json
echo "{\n    \"zone\": \"IE\"\n}" >          ./gen/ASffaa_0_1002/geolocation.json
echo "{\n    \"zone\": \"US-MIDA-PJM\"\n}" > ./gen/ASffaa_0_1003/geolocation.json
echo "{\n    \"zone\": \"US-NW-PACW\"\n}" >  ./gen/ASffaa_0_1005/geolocation.json
echo "{\n    \"zone\": \"DE\"\n}" >          ./gen/ASffaa_0_1001/geolocation.json
echo "{\n    \"zone\": \"CH\"\n}" >          ./gen/ASffaa_0_1108/geolocation.json
echo "{\n    \"zone\": \"CH\"\n}" >          ./gen/ASffaa_0_1101/geolocation.json
echo "{\n    \"zone\": \"JP-TK\"\n}" >       ./gen/ASffaa_0_1501/geolocation.json
echo "{\n    \"zone\": \"DE\"\n}" >          ./gen/ASffaa_0_130b/geolocation.json
echo "{\n    \"zone\": \"NL\"\n}" >          ./gen/ASffaa_0_1302/geolocation.json
echo "{\n    \"zone\": \"DE\"\n}" >          ./gen/ASffaa_0_1301/geolocation.json
echo "{\n    \"zone\": \"US-NW-SCL\"\n}" >   ./gen/ASffaa_0_2002/geolocation.json
echo "{\n    \"zone\": \"HK\"\n}" >          ./gen/ASffaa_0_2003/geolocation.json
echo "{\n    \"zone\": \"US-MIDA-PJM\"\n}" > ./gen/ASffaa_0_2004/geolocation.json
echo "{\n    \"zone\": \"KR\"\n}" >          ./gen/ASffaa_0_2001/geolocation.json
echo "{\n    \"zone\": \"HK\"\n}" >          ./gen/ASffaa_0_1902/geolocation.json
